/* The companies' own marks (Round 38). Each is a 64 square tile in
   assets/logos: the brand's ground colour as the first <rect>, then its mark,
   taken from the brand's own vector where one is published and traced from
   its own picture where it is not (assets/logos/SOURCES.md says which). This
   writes the copy the app imports, with the ground kept apart so a tile can
   be drawn without it, and ids left as __ID__ for the screen to make unique
   (two tiles on one web page must not share a gradient). Run `npm run logos`
   after changing a tile. */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const dir = new URL('../assets/logos/', import.meta.url).pathname;
const out = new URL('../src/design/logos.ts', import.meta.url).pathname;
const tiles = {};
for (const f of readdirSync(dir)
  .filter(f => f.endsWith('.svg'))
  .sort()) {
  const svg = readFileSync(join(dir, f), 'utf8').trim();
  const m = svg.match(/^<svg[^>]*viewBox="0 0 64 64"[^>]*><rect width="64" height="64" fill="(#[0-9a-fA-F]{6})"\/>([\s\S]*)<\/svg>$/);
  if (!m) throw new Error(`logos: ${f} is not a 64 tile with its ground first`);
  tiles[f.replace(/\.svg$/, '')] = { ground: m[1].toLowerCase(), body: m[2] };
}
const head = `/* Generated by scripts/generate-logos.mjs from assets/logos. Do not edit by hand.
   Each company's tile: its ground colour, and its mark drawn in a 64 square
   (__ID__ is made unique per tile drawn). */

`;
writeFileSync(out, head + `export const LOGOS = ${JSON.stringify(tiles, null, 2)} as const;\n\nexport type LogoName = keyof typeof LOGOS;\n`);
console.log(`logos: ${Object.keys(tiles).length} tiles`);
