/* The icon set is the glyphs exported from the Figma file. It lives once, in
   ../../src/icons.js at the repository root, and this writes the copy this app
   imports so the two can never drift apart. Run `npm run icons` after
   re-exporting. */
import { writeFileSync } from 'fs';
import { ICONS } from '../../src/icons.js';

/* The set is drawn to one rule — a glyph's line is 0.075 of its box and a
   bare mark's 0.10 — but the export writes no width on the glyph paths, so
   they would draw at the SVG default, a third of what the file shows, and
   thin beside the marks. The widths go back in here, every line gets round
   ends and joins, and every line takes the colour it is given: a chevron
   exported in grey or an arrow in white is drawn in whatever the screen
   asks for. Fills are left alone. */
const GLYPH = 1.8;
function normalise(svg) {
  return svg.replace(/<(path|circle|line|rect|polyline|ellipse)\b([^>]*?)(\/?)>/g, (whole, tag, attrs, close) => {
    if (!/\bstroke=/.test(attrs)) return whole;
    let a = attrs.replace(/\bstroke="(?:white|#[0-9a-fA-F]{3,6})"/, 'stroke="currentColor"');
    if (!/stroke-width=/.test(a)) a += ` stroke-width="${GLYPH}"`;
    if (!/stroke-linecap=/.test(a)) a += ' stroke-linecap="round"';
    if (!/stroke-linejoin=/.test(a)) a += ' stroke-linejoin="round"';
    return `<${tag}${a}${close}>`;
  });
}

/* The bar draws Home, Activities and Settings solid. The file has a solid
   house and a solid clock but only the outline gear, so the solid gear is
   derived here from the file's own rather than drawn: its cog filled, with
   the same line run round its edge so it keeps the outline's size, and its
   centre left open. */
function solidGear(svg) {
  const [hole, cog] = [...svg.matchAll(/<path d="([^"]+)"/g)].map(m => m[1]);
  if (!hole || !cog) throw new Error('icons: the gear has changed shape; look at solidGear');
  return `<path d="${cog}${hole}" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"/><path d="${cog}" stroke="currentColor" fill="none"/>`;
}
const DERIVED = { 'gear-filled': solidGear(ICONS.gear) };
const ALL = { ...ICONS, ...DERIVED };

/* A solid glyph's details — the face in Face ID, the stripe on the card, the
   tick in the shield, the hands on the clock, the house's door — are drawn
   in the file as white lines and shapes laid over the fill. Drawn as they
   are, they are white on a white screen and a white smear on a dark one, and
   once every line takes the screen's colour they vanish into the fill. So
   they are cut out of it instead: the white pieces become a mask, and what
   shows through is whatever the glyph sits on. The mask's id is a
   placeholder the Icon makes unique for each glyph it draws. */
const CUT = '__CUT__';
const WHITE = /\b(stroke|fill)="(?:white|#fff|#ffffff)"/i;
function cutOut(svg) {
  const parts = [...svg.matchAll(/<(path|circle|line|rect|polyline|ellipse)\b[^>]*\/>/g)].map(m => m[0]);
  if (!parts.some(p => /\bfill="currentColor"/.test(p)) || !parts.some(p => WHITE.test(p))) return normalise(svg);
  const cuts = parts.filter(p => WHITE.test(p)).map(p => normalise(p).replace(/\b(stroke|fill)="(?:currentColor|white|#fff|#ffffff)"/gi, '$1="#000"'));
  const ink = parts.filter(p => !WHITE.test(p)).map(normalise);
  return `<defs><mask id="${CUT}" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect width="24" height="24" fill="#fff"/>${cuts.join('')}</mask></defs><g mask="url(#${CUT})">${ink.join('')}</g>`;
}

const names = Object.keys(ALL).sort();
const body = names.map(n => `  ${JSON.stringify(n)}: ${JSON.stringify(cutOut(ALL[n]))},`).join('\n');

writeFileSync(
  new URL('../src/icons.ts', import.meta.url),
  `/* Generated by scripts/generate-icons.mjs. Do not edit by hand.
   These are the glyphs from the Figma file, exported as SVG, with the
   line widths the file draws them at put back on the paths, and a solid
   glyph's white details cut out of it (${CUT} is made unique per glyph drawn). */

export const ICONS = {
${body}
} as const;

export type IconName = keyof typeof ICONS;
export const iconNames = Object.keys(ICONS) as IconName[];
`,
);
console.log(`icons: wrote ${names.length} glyphs`);
