/* The icon set is the glyphs exported from the Figma file. It lives once, in
   ../../src/icons.js at the repository root, and this writes the copy this app
   imports so the two can never drift apart. Run `npm run icons` after
   re-exporting. */
import { writeFileSync } from 'fs';
import { ICONS } from '../../src/icons.js';

/* The set is drawn to one rule — a glyph's line is 0.075 of its box and a
   bare mark's 0.10 — but the export writes no width on the glyph paths, so
   they would draw at the SVG default, a third of what the file shows, and
   thin beside the marks. The widths go back in here, every line gets round
   ends and joins, and every line takes the colour it is given: a chevron
   exported in grey or an arrow in white is drawn in whatever the screen
   asks for. Fills are left alone. */
const GLYPH = 1.8;
function normalise(svg) {
  return svg.replace(/<(path|circle|line|rect|polyline|ellipse)\b([^>]*?)(\/?)>/g, (whole, tag, attrs, close) => {
    if (!/\bstroke=/.test(attrs)) return whole;
    let a = attrs.replace(/\bstroke="(?:white|#[0-9a-fA-F]{3,6})"/, 'stroke="currentColor"');
    if (!/stroke-width=/.test(a)) a += ` stroke-width="${GLYPH}"`;
    if (!/stroke-linecap=/.test(a)) a += ' stroke-linecap="round"';
    if (!/stroke-linejoin=/.test(a)) a += ' stroke-linejoin="round"';
    return `<${tag}${a}${close}>`;
  });
}

const names = Object.keys(ICONS).sort();
const body = names.map(n => `  ${JSON.stringify(n)}: ${JSON.stringify(normalise(ICONS[n]))},`).join('\n');

writeFileSync(
  new URL('../src/icons.ts', import.meta.url),
  `/* Generated by scripts/generate-icons.mjs. Do not edit by hand.
   These are the glyphs from the Figma file, exported as SVG, with the
   line widths the file draws them at put back on the paths. */

export const ICONS = {
${body}
} as const;

export type IconName = keyof typeof ICONS;
export const iconNames = Object.keys(ICONS) as IconName[];
`,
);
console.log(`icons: wrote ${names.length} glyphs`);
