/* Which company a name is (Round 38), from the words the app already holds: a bank's
   name, a network, a biller's or a disco's id or name, a merchant, a coin or
   a chain. The whole name first, then without its last word or two ("MTN
   data", "DStv Compact", "WAEC result checker"), so a line named for what was
   bought still finds whose it was. Nothing for a name it does not know, and
   the row keeps its glyph. Apart from the drawing (Logo.tsx), so the tests
   and the lines' own rule can ask without a screen. */
import type { LogoName } from './logos';

const NAMES: Record<string, LogoName> = {
  /* banks */
  access: 'access',
  accessbank: 'access',
  ecobank: 'ecobank',
  fidelity: 'fidelity',
  fidelitybank: 'fidelity',
  firstbank: 'firstbank',
  firstbankofnigeria: 'firstbank',
  fcmb: 'fcmb',
  firstcitymonumentbank: 'fcmb',
  gtbank: 'gtbank',
  gtco: 'gtbank',
  guarantytrust: 'gtbank',
  guarantytrustbank: 'gtbank',
  heritage: 'heritage',
  heritagebank: 'heritage',
  keystone: 'keystone',
  keystonebank: 'keystone',
  kuda: 'kuda',
  kudabank: 'kuda',
  moniepoint: 'moniepoint',
  opay: 'opay',
  palmpay: 'palmpay',
  polaris: 'polaris',
  polarisbank: 'polaris',
  providus: 'providus',
  providusbank: 'providus',
  providusunity: 'providus',
  /* Unity Bank is one bank with Providus now, and wears its mark */
  unity: 'providus',
  unitybank: 'providus',
  stanbic: 'stanbic',
  stanbicibtc: 'stanbic',
  stanbicibtcbank: 'stanbic',
  sterling: 'sterling',
  sterlingbank: 'sterling',
  uba: 'uba',
  unitedbankforafrica: 'uba',
  union: 'union',
  unionbank: 'union',
  wema: 'wema',
  wemabank: 'wema',
  alat: 'wema',
  zenith: 'zenith',
  zenithbank: 'zenith',
  beetle: 'beetle',
  /* networks; 9mobile is T2 now, and wears its mark */
  mtn: 'mtn',
  airtel: 'airtel',
  glo: 'glo',
  globacom: 'glo',
  '9mobile': 't2',
  t2: 't2',
  /* billers */
  dstv: 'dstv',
  showmax: 'showmax',
  spectranet: 'spectranet',
  lawma: 'lawma',
  waec: 'waec',
  bet9ja: 'bet9ja',
  /* the electricity companies, by id, short name and name */
  ikeja: 'ikeja',
  ikejaelectric: 'ikeja',
  eko: 'eko',
  ekedc: 'eko',
  ekoelectric: 'eko',
  abuja: 'abuja',
  aedc: 'abuja',
  jos: 'jos',
  jed: 'jos',
  kano: 'kano',
  kedco: 'kano',
  ibadan: 'ibadan',
  ibedc: 'ibadan',
  enugu: 'enugu',
  eedc: 'enugu',
  portharcourt: 'portharcourt',
  phed: 'portharcourt',
  benin: 'benin',
  bedc: 'benin',
  kaduna: 'kaduna',
  kaedco: 'kaduna',
  yola: 'yola',
  yedc: 'yola',
  /* merchants and others */
  netflix: 'netflix',
  spotify: 'spotify',
  apple: 'apple',
  googleplay: 'googleplay',
  google: 'google',
  whatsapp: 'whatsapp',
  mastercard: 'mastercard',
  /* the rest of the banks, the payment service banks and the fintechs (Round 39) */
  '9psb': 'ninepsb',
  '9paymentservicebank': 'ninepsb',
  zapbybitnob: 'bitnob',
  bitnob: 'bitnob',
  branch: 'branch',
  citibank: 'citi',
  citi: 'citi',
  coronationmerchantbank: 'coronation',
  coronation: 'coronation',
  creditdirect: 'creditdirect',
  flutterwave: 'flutterwave',
  flutterwavemfb: 'flutterwave',
  carbon: 'carbon',
  paga: 'paga',
  pocketbypiggyvest: 'piggyvest',
  piggyvest: 'piggyvest',
  sparkle: 'sparkle',
  summitbank: 'summit',
  fairmoney: 'fairmoney',
  gomoney: 'gomoney',
  paystack: 'paystack',
  paystackmfb: 'paystack',
  paystacktitan: 'paystack',
  vfd: 'vfd',
  vfdmfb: 'vfd',
  vbank: 'vfd',
  accion: 'accion',
  accionmfb: 'accion',
  ekondo: 'ekondo',
  ekondomfb: 'ekondo',
  eyowo: 'eyowo',
  globus: 'globus',
  globusbank: 'globus',
  jaiz: 'jaiz',
  jaizbank: 'jaiz',
  lotus: 'lotus',
  lotusbank: 'lotus',
  momopsb: 'momopsb',
  mtnmomo: 'momopsb',
  optimus: 'optimus',
  optimusbank: 'optimus',
  parallex: 'parallex',
  parallexbank: 'parallex',
  premiumtrust: 'premiumtrust',
  premiumtrustbank: 'premiumtrust',
  rubies: 'rubies',
  rubiesmfb: 'rubies',
  safehaven: 'safehaven',
  safehavenmfb: 'safehaven',
  standardchartered: 'standardchartered',
  standardcharteredbank: 'standardchartered',
  stellas: 'stellas',
  stellasmfb: 'stellas',
  suntrust: 'suntrust',
  suntrustbank: 'suntrust',
  taj: 'taj',
  tajbank: 'taj',
  tangerine: 'tangerine',
  tangerinemoney: 'tangerine',
  abbey: 'abbey',
  abbeymortgagebank: 'abbey',
  smartcashpsb: 'airtel',
  airtelsmartcash: 'airtel',
  accessbankdiamond: 'access',
  diamond: 'access',
  alatbywema: 'wema',
  fcmbmfb: 'fcmb',
  /* the twelfth electricity company */
  aba: 'aba',
  abapower: 'aba',
  aple: 'aba',
  /* more of what a card pays (Round 39) */
  youtube: 'youtube',
  youtubepremium: 'youtube',
  applemusic: 'applemusic',
  icloud: 'icloud',
  uber: 'uber',
  aliexpress: 'aliexpress',
  audiomack: 'audiomack',
  deezer: 'deezer',
  duolingo: 'duolingo',
  coursera: 'coursera',
  udemy: 'udemy',
  x: 'x',
  zoom: 'zoom',
  notion: 'notion',
  figma: 'figma',
  github: 'github',
  steam: 'steam',
  playstation: 'playstation',
  airbnb: 'airbnb',
  bookingcom: 'bookingdotcom',
  booking: 'bookingdotcom',
  upwork: 'upwork',
  fiverr: 'fiverr',
  shopify: 'shopify',
  etsy: 'etsy',
  ebay: 'ebay',
  tiktok: 'tiktok',
  snapchat: 'snapchat',
  telegram: 'telegram',
  discord: 'discord',
  twitch: 'twitch',
  claude: 'claude',
  perplexity: 'perplexity',
  grammarly: 'grammarly',
  dropbox: 'dropbox',
  googleone: 'google',
  googledrive: 'googledrive',
  appletv: 'appletv',
  paramount: 'paramountplus',
  paramountplus: 'paramountplus',
  crunchyroll: 'crunchyroll',
  patreon: 'patreon',
  substack: 'substack',
  medium: 'medium',
  namecheap: 'namecheap',
  godaddy: 'godaddy',
  hostinger: 'hostinger',
  cloudflare: 'cloudflare',
  digitalocean: 'digitalocean',
  vercel: 'vercel',
  googlecloud: 'googlecloud',
  /* coins and chains */
  usdc: 'usdc',
  usdcoin: 'usdc',
  usdt: 'usdt',
  tether: 'usdt',
  tetherusd: 'usdt',
  pyusd: 'pyusd',
  paypalusd: 'pyusd',
  solana: 'solana',
  base: 'base',
  tron: 'tron',
  trontrc20: 'tron',
  ethereum: 'ethereum',
  ethereumerc20: 'ethereum',
};

const key = (words: string[]) => words.join('').toLowerCase();

export function logoOf(name: string | null | undefined): LogoName | undefined {
  if (!name) return undefined;
  const words = name
    .replace(/[^A-Za-z0-9 ]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  for (let drop = 0; drop <= 2 && words.length - drop > 0; drop++) {
    const hit = NAMES[key(words.slice(0, words.length - drop))];
    if (hit) return hit;
  }
  return undefined;
}
