/* The icon set is the ninety-seven glyphs exported from the Figma file. It
   lives once, in ../../src/icons.js, and this writes the React Native copy so
   the two can never drift apart. Run `npm run icons` after re-exporting. */
import { writeFileSync } from 'fs';
import { ICONS } from '../../src/icons.js';

const names = Object.keys(ICONS).sort();
const body = names.map(n => `  ${JSON.stringify(n)}: ${JSON.stringify(ICONS[n])},`).join('\n');

writeFileSync(new URL('../src/icons.ts', import.meta.url), `/* Generated by scripts/generate-icons.mjs. Do not edit by hand.
   These are the glyphs from the Figma file, exported as SVG. */

export const ICONS = {
${body}
} as const;

export type IconName = keyof typeof ICONS;
export const iconNames = Object.keys(ICONS) as IconName[];
`);
console.log(`icons: wrote ${names.length} glyphs`);
