/* Every bank and money app a Nigerian transfer can reach (Round 39: the
   owner's word, there are far more banks than the twenty the app knew).
   The list is the one the NIBSS transfer network answers for, as Paystack
   publishes it, by the names people call them (GTBank, not Guaranty Trust;
   MFB for a microfinance bank). Heritage Bank is gone: its licence was
   revoked in 2024. Unity Bank is listed until its merger with Providus is
   done.

   The code is the bank's own: three digits for the commercial, merchant and
   non-interest banks, whose account numbers carry a check digit worked from
   it; longer for the rest, whose numbers it does not decide. */

export type BankKind = 'bank' | 'merchant' | 'noninterest' | 'mfb' | 'mortgage' | 'finance' | 'fintech' | 'psb';

export type Bank = {
  name: string;
  /** the code the check digit is worked from: three digits for the banks, longer for the newer ones */
  code: string;
  kind: BankKind;
  /** the newer banks that hand out phone numbers as account numbers */
  phone?: boolean;
};

/** What kind of bank it is, in the words the list shows under its name. */
export const KIND_WORDS: Record<BankKind, string> = {
  bank: 'Commercial bank',
  merchant: 'Merchant bank',
  noninterest: 'Non-interest bank',
  mfb: 'Microfinance bank',
  mortgage: 'Mortgage bank',
  finance: 'Finance company',
  fintech: 'Money app',
  psb: 'Payment service bank',
};

export const BANK_LIST: Bank[] = [
  { name: '5TT MFB', code: '51455', kind: 'mfb' },
  { name: '78 Finance Company', code: '40195', kind: 'finance' },
  { name: '9jaPay MFB', code: '090629', kind: 'mfb' },
  { name: '9PSB', code: '120001', kind: 'psb', phone: true },
  { name: 'Abbey Mortgage Bank', code: '404', kind: 'mortgage' },
  { name: 'Above Only MFB', code: '51204', kind: 'mfb' },
  { name: 'Abulesoro MFB', code: '51312', kind: 'mfb' },
  { name: 'Access Bank', code: '044', kind: 'bank' },
  { name: 'Access Bank (Diamond)', code: '063', kind: 'bank' },
  { name: 'Accion MFB', code: '602', kind: 'mfb' },
  { name: 'Adamawa Mortgage Bank', code: '90102', kind: 'mortgage' },
  { name: 'Advancly MFB', code: '090759', kind: 'mfb' },
  { name: 'Aella MFB', code: '50315', kind: 'mfb' },
  { name: 'AG Mortgage Bank', code: '90077', kind: 'mortgage' },
  { name: 'Ahmadu Bello University MFB', code: '50036', kind: 'mfb' },
  { name: 'AKU MFB', code: '51336', kind: 'mfb' },
  { name: 'Akuchukwu MFB', code: '090561', kind: 'mfb' },
  { name: 'Al-Barakah MFB', code: '50055', kind: 'mfb' },
  { name: 'ALAT by Wema', code: '035A', kind: 'fintech' },
  { name: 'Alert MFB', code: '51074', kind: 'mfb' },
  { name: 'Allworkers MFB', code: '50059', kind: 'mfb' },
  { name: 'Alpha Morgan Bank', code: '108', kind: 'bank' },
  { name: 'Alternative Bank', code: '000304', kind: 'noninterest' },
  { name: 'Amju Unique MFB', code: '50926', kind: 'mfb' },
  { name: 'Aramoko MFB', code: '50083', kind: 'mfb' },
  { name: 'ASO Savings and Loans', code: '401', kind: 'mortgage' },
  { name: 'Asset Matrix MFB', code: '90287', kind: 'mfb' },
  { name: 'Assets MFB', code: '50092', kind: 'mfb' },
  { name: 'Astrapolaris MFB', code: 'MFB50094', kind: 'mfb' },
  { name: 'ATBU MFB', code: '90451', kind: 'mfb' },
  { name: 'Avuenegbe MFB', code: '090478', kind: 'mfb' },
  { name: 'Awacash MFB', code: '51351', kind: 'mfb' },
  { name: 'Aztec MFB', code: '51337', kind: 'mfb' },
  { name: 'Bainescredit MFB', code: '51229', kind: 'mfb' },
  { name: 'Banc Corp MFB', code: '50117', kind: 'mfb' },
  { name: 'Bank of Agriculture', code: '90367', kind: 'bank' },
  { name: 'Bank78 MFB', code: '11072', kind: 'mfb' },
  { name: 'Bankit MFB', code: '50572', kind: 'mfb' },
  { name: 'Bankly MFB', code: '51341', kind: 'mfb' },
  { name: 'Baobab MFB', code: 'MFB50992', kind: 'mfb' },
  { name: 'BC Kash MFB', code: '51212', kind: 'mfb' },
  { name: 'BellBank MFB', code: '51100', kind: 'mfb' },
  { name: 'Benysta MFB', code: '51267', kind: 'mfb' },
  { name: 'Berachah MFB', code: '50122', kind: 'mfb' },
  { name: 'Beststar MFB', code: '50123', kind: 'mfb' },
  { name: 'Bloc MFB', code: '51411', kind: 'mfb' },
  { name: 'Bold MFB', code: '50725', kind: 'mfb' },
  { name: 'Boost MFB', code: '51449', kind: 'mfb' },
  { name: 'Bosak MFB', code: '650', kind: 'mfb' },
  { name: 'Bowen MFB', code: '50931', kind: 'mfb' },
  { name: 'Branch', code: 'FC40163', kind: 'finance' },
  { name: 'Brent Mortgage Bank', code: '90070', kind: 'mortgage' },
  { name: 'BuyPower MFB', code: '50645', kind: 'mfb' },
  { name: 'Bway MFB', code: '90774', kind: 'mfb' },
  { name: 'Carbon', code: '565', kind: 'fintech' },
  { name: 'Cashbridge MFB', code: '51353', kind: 'mfb' },
  { name: 'Cashconnect MFB', code: '865', kind: 'mfb' },
  { name: 'Cedrus MFB', code: '51437', kind: 'mfb' },
  { name: 'CEMCS MFB', code: '50823', kind: 'mfb' },
  { name: 'Centrum Finance', code: '050032', kind: 'finance' },
  { name: 'Chams Mobile MFB', code: '100036', kind: 'mfb' },
  { name: 'Chanelle MFB', code: '50171', kind: 'mfb' },
  { name: 'Chikum MFB', code: '312', kind: 'mfb' },
  { name: 'Citibank', code: '023', kind: 'bank' },
  { name: 'Citycode Mortgage Bank', code: '070027', kind: 'mortgage' },
  { name: 'Civic MFB', code: '50186', kind: 'mfb' },
  { name: 'Consumer MFB', code: '50910', kind: 'mfb' },
  { name: 'Cool MFB', code: '51458', kind: 'mfb' },
  { name: 'Cooperative Mortgage Bank', code: '90089', kind: 'mortgage' },
  { name: 'Corestep MFB', code: '50204', kind: 'mfb' },
  { name: 'Coronation Merchant Bank', code: '559', kind: 'merchant' },
  { name: 'County Finance', code: 'FC40128', kind: 'finance' },
  { name: 'Credit Direct', code: '40119', kind: 'finance' },
  { name: 'Crescent MFB', code: '51297', kind: 'mfb' },
  { name: 'Crust MFB', code: '090560', kind: 'mfb' },
  { name: 'Crutech MFB', code: '50216', kind: 'mfb' },
  { name: 'Dash MFB', code: '51368', kind: 'mfb' },
  { name: 'Davenport MFB', code: '51334', kind: 'mfb' },
  { name: 'Dillon MFB', code: '51450', kind: 'mfb' },
  { name: 'Dot MFB', code: '50162', kind: 'mfb' },
  { name: 'EBSU MFB', code: '50922', kind: 'mfb' },
  { name: 'Ecobank', code: '050', kind: 'bank' },
  { name: 'Ekimogun MFB', code: '50263', kind: 'mfb' },
  { name: 'Ekondo MFB', code: '098', kind: 'mfb' },
  { name: 'Eso-e MFB', code: '50280', kind: 'mfb' },
  { name: 'Ethica MFB', code: '51475', kind: 'mfb' },
  { name: 'Excel Finance Bank', code: '090678', kind: 'finance' },
  { name: 'Eyowo', code: '50126', kind: 'fintech', phone: true },
  { name: 'FairMoney', code: '51318', kind: 'mfb' },
  { name: 'FCMB', code: '214', kind: 'bank' },
  { name: 'FCMB MFB', code: '51241', kind: 'mfb' },
  { name: 'Fedeth MFB', code: '50298', kind: 'mfb' },
  { name: 'Fewchore Finance Company', code: '050002', kind: 'finance' },
  { name: 'FFS MFB', code: '51110', kind: 'mfb' },
  { name: 'Fidelity Bank', code: '070', kind: 'bank' },
  { name: 'Firmus MFB', code: '51314', kind: 'mfb' },
  { name: 'First Bank', code: '011', kind: 'bank' },
  { name: 'First Option MFB', code: '50934', kind: 'mfb' },
  { name: 'First Royal MFB', code: '090164', kind: 'mfb' },
  { name: 'Firstmidas MFB', code: '51333', kind: 'mfb' },
  { name: 'FirstTrust Mortgage Bank', code: '413', kind: 'mortgage' },
  { name: 'Flutterwave MFB', code: '090567', kind: 'mfb' },
  { name: 'Fortress MFB', code: 'D53', kind: 'mfb' },
  { name: 'FSDH Merchant Bank', code: '501', kind: 'merchant' },
  { name: 'Futminna MFB', code: '832', kind: 'mfb' },
  { name: 'Garun Mallam MFB', code: 'MFB51093', kind: 'mfb' },
  { name: 'Gateway Mortgage Bank', code: '812', kind: 'mortgage' },
  { name: 'Globus Bank', code: '00103', kind: 'bank' },
  { name: 'Glory MFB', code: '90278', kind: 'mfb' },
  { name: 'Goldman MFB', code: '090574', kind: 'mfb' },
  { name: 'Gombe MFB', code: '90586', kind: 'mfb' },
  { name: 'GoMoney', code: '100022', kind: 'fintech' },
  { name: 'Good Shepherd MFB', code: '090664', kind: 'mfb' },
  { name: 'Goodnews MFB', code: '50739', kind: 'mfb' },
  { name: 'Grants MFB', code: '90335', kind: 'mfb' },
  { name: 'Greenwich Merchant Bank', code: '562', kind: 'merchant' },
  { name: 'Grooming MFB', code: '51276', kind: 'mfb' },
  { name: 'GTBank', code: '058', kind: 'bank' },
  { name: 'GTI MFB', code: '50368', kind: 'mfb' },
  { name: 'Hackman MFB', code: '51251', kind: 'mfb' },
  { name: 'Haggai Mortgage Bank', code: '90065', kind: 'mortgage' },
  { name: 'Hasal MFB', code: '50383', kind: 'mfb' },
  { name: 'Hayat Trust MFB', code: '51364', kind: 'mfb' },
  { name: 'HopePSB', code: '120002', kind: 'psb', phone: true },
  { name: 'Ibank MFB', code: '51211', kind: 'mfb' },
  { name: 'IBBU MFB', code: '51279', kind: 'mfb' },
  { name: 'Ibile MFB', code: '51244', kind: 'mfb' },
  { name: 'Ibom Mortgage Bank', code: '90012', kind: 'mortgage' },
  { name: 'Ikoyi Osun MFB', code: '50439', kind: 'mfb' },
  { name: 'Ilaro Poly MFB', code: '50442', kind: 'mfb' },
  { name: 'Imowo MFB', code: '50453', kind: 'mfb' },
  { name: 'Imperial Homes Mortgage Bank', code: '415', kind: 'mortgage' },
  { name: 'Ineba Gogo MFB', code: '51462', kind: 'mfb' },
  { name: 'Infinity MFB', code: '50457', kind: 'mfb' },
  { name: 'Infinity Trust Mortgage Bank', code: '070016', kind: 'mortgage' },
  { name: 'ISUA MFB', code: '090701', kind: 'mfb' },
  { name: 'Jaiz Bank', code: '301', kind: 'noninterest' },
  { name: 'Jubilee Life Mortgage Bank', code: '402', kind: 'mortgage' },
  { name: 'Kadpoly MFB', code: '50502', kind: 'mfb' },
  { name: 'Kanopoly MFB', code: '51308', kind: 'mfb' },
  { name: 'KAYI MFB', code: '90667', kind: 'mfb' },
  { name: 'Kayvee MFB', code: '5129', kind: 'mfb' },
  { name: 'Kebbi Homes Savings and Loans', code: '90028', kind: 'mortgage' },
  { name: 'Keystone Bank', code: '082', kind: 'bank' },
  { name: 'Kolomoni MFB', code: '899', kind: 'mfb' },
  { name: 'KongaPay', code: '100025', kind: 'fintech' },
  { name: 'Kredi Money MFB', code: '50200', kind: 'mfb' },
  { name: 'Kuda', code: '090267', kind: 'fintech', phone: true },
  { name: 'LBIC', code: '90052', kind: 'mortgage' },
  { name: 'Lemmy MFB', code: '091003', kind: 'mfb' },
  { name: 'Letshego MFB', code: '090420', kind: 'mfb' },
  { name: 'Links MFB', code: '50549', kind: 'mfb' },
  { name: 'Living Trust Mortgage Bank', code: '031', kind: 'mortgage' },
  { name: 'LOMA MFB', code: '50491', kind: 'mfb' },
  { name: 'Lotus Bank', code: '303', kind: 'noninterest' },
  { name: 'Maal MFB', code: '51444', kind: 'mfb' },
  { name: 'Mahfuz MFB', code: '90825', kind: 'mfb' },
  { name: 'Mainstreet MFB', code: '090171', kind: 'mfb' },
  { name: 'Mayden MFB', code: '51474', kind: 'mfb' },
  { name: 'Mayfair MFB', code: '50563', kind: 'mfb' },
  { name: 'Mayfresh Mortgage Bank', code: '90003', kind: 'mortgage' },
  { name: 'Mega MFB', code: '50570', kind: 'mfb' },
  { name: 'Michael Okpara UniAgric MFB', code: 'MFB51116M', kind: 'mfb' },
  { name: 'Mint MFB', code: '50304', kind: 'mfb' },
  { name: 'Mint-finex MFB', code: '09', kind: 'mfb' },
  { name: 'MoMo PSB', code: '120003', kind: 'psb', phone: true },
  { name: 'Money Master PSB', code: '946', kind: 'psb' },
  { name: 'Moniepoint', code: '090405', kind: 'fintech', phone: true },
  { name: 'Movasco MFB', code: '90979', kind: 'mfb' },
  { name: 'Mutual Benefits MFB', code: '090190', kind: 'mfb' },
  { name: 'NDCC MFB', code: '090679', kind: 'mfb' },
  { name: 'NET MFB', code: '51361', kind: 'mfb' },
  { name: 'Nigerian Navy MFB', code: '51142', kind: 'mfb' },
  { name: 'Nirsal MFB', code: '51304', kind: 'mfb' },
  { name: 'Nombank MFB', code: '50072', kind: 'mfb' },
  { name: 'Nova Bank', code: '561', kind: 'bank' },
  { name: 'Novus MFB', code: '51371', kind: 'mfb' },
  { name: 'NPF MFB', code: '50629', kind: 'mfb' },
  { name: 'NSUK MFB', code: '51261', kind: 'mfb' },
  { name: 'NUVION MFB', code: '51392', kind: 'mfb' },
  { name: 'Olabisi Onabanjo University MFB', code: '50689', kind: 'mfb' },
  { name: 'Oluchukwu MFB', code: '50697', kind: 'mfb' },
  { name: 'OPay', code: '100004', kind: 'fintech', phone: true },
  { name: 'Optimus Bank', code: '107', kind: 'bank' },
  { name: 'Pact MFB', code: '51477', kind: 'mfb' },
  { name: 'Paga', code: '100002', kind: 'fintech', phone: true },
  { name: 'PalmPay', code: '100033', kind: 'fintech', phone: true },
  { name: 'Parallex Bank', code: '104', kind: 'bank' },
  { name: 'Pathfinder MFB', code: '090680', kind: 'mfb' },
  { name: 'Patrickgold MFB', code: '90317', kind: 'mfb' },
  { name: 'Paystack MFB', code: '51457', kind: 'mfb' },
  { name: 'Paystack-Titan', code: '100039', kind: 'fintech' },
  { name: 'Peace MFB', code: '50743', kind: 'mfb' },
  { name: 'Pecantrust MFB', code: '51226', kind: 'mfb' },
  { name: 'Personal Trust MFB', code: '51146', kind: 'mfb' },
  { name: 'Petra MFB', code: '50746', kind: 'mfb' },
  { name: 'Pettysave MFB', code: 'MFB51452', kind: 'mfb' },
  { name: 'PFI Finance Company', code: '050021', kind: 'finance' },
  { name: 'Platinum Mortgage Bank', code: '268', kind: 'mortgage' },
  { name: 'Pocket by PiggyVest', code: '00716', kind: 'fintech' },
  { name: 'Polaris Bank', code: '076', kind: 'bank' },
  { name: 'Polyunwana MFB', code: '50864', kind: 'mfb' },
  { name: 'PremiumTrust Bank', code: '105', kind: 'bank' },
  { name: 'Prospa Capital MFB', code: '50739', kind: 'mfb' },
  { name: 'Prosperis Finance', code: '050023', kind: 'finance' },
  { name: 'Providus Bank', code: '101', kind: 'bank' },
  { name: 'QuickFund MFB', code: '51293', kind: 'mfb' },
  { name: 'Rand Merchant Bank', code: '502', kind: 'merchant' },
  { name: 'Randalpha MFB', code: '090496', kind: 'mfb' },
  { name: 'Rank MFB', code: '50130', kind: 'mfb' },
  { name: 'ReadyCash', code: '311', kind: 'fintech' },
  { name: 'Refuge Mortgage Bank', code: '90067', kind: 'mortgage' },
  { name: 'Rehoboth MFB', code: '50761', kind: 'mfb' },
  { name: 'Renmoney', code: '51049', kind: 'mfb' },
  { name: 'Rephidim MFB', code: '50994', kind: 'mfb' },
  { name: 'Retrust MFB', code: '51375', kind: 'mfb' },
  { name: 'Rex MFB', code: '51108', kind: 'mfb' },
  { name: 'Rigo MFB', code: '51286', kind: 'mfb' },
  { name: 'Rockshield MFB', code: '50767', kind: 'mfb' },
  { name: 'RSU MFB', code: '50622', kind: 'mfb' },
  { name: 'Rubies MFB', code: '125', kind: 'mfb' },
  { name: 'Safe Haven MFB', code: '51113', kind: 'mfb' },
  { name: 'Sage Grey Finance', code: '40165', kind: 'finance' },
  { name: 'Shield MFB', code: '50582', kind: 'mfb' },
  { name: 'Signature Bank', code: '106', kind: 'bank' },
  { name: 'SmartCash PSB', code: '120004', kind: 'psb', phone: true },
  { name: 'Solid Allianze MFB', code: '51062', kind: 'mfb' },
  { name: 'Solid Rock MFB', code: '50800', kind: 'mfb' },
  { name: 'Source MFB', code: '90641', kind: 'mfb' },
  { name: 'Sparkle', code: '51310', kind: 'mfb' },
  { name: 'Spectrum MFB', code: '50756', kind: 'mfb' },
  { name: 'Springfield MFB', code: '51429', kind: 'mfb' },
  { name: 'Stanbic IBTC', code: '221', kind: 'bank' },
  { name: 'Standard Chartered Bank', code: '068', kind: 'bank' },
  { name: 'Stanford MFB', code: '090162', kind: 'mfb' },
  { name: 'Stateside MFB', code: '50809', kind: 'mfb' },
  { name: 'STB Mortgage Bank', code: '070022', kind: 'mortgage' },
  { name: 'Stellas MFB', code: '51253', kind: 'mfb' },
  { name: 'Sterling Bank', code: '232', kind: 'bank' },
  { name: 'Summit Bank', code: '00305', kind: 'bank' },
  { name: 'SunTrust Bank', code: '100', kind: 'bank' },
  { name: 'Supreme MFB', code: '50968', kind: 'mfb' },
  { name: 'Sycamore MFB', code: '51056', kind: 'mfb' },
  { name: 'TagPay', code: '100023', kind: 'fintech' },
  { name: 'TAJ Bank', code: '302', kind: 'noninterest' },
  { name: 'Tangerine Money', code: '51269', kind: 'fintech' },
  { name: 'Tatum Bank', code: '109', kind: 'bank' },
  { name: 'TENN', code: '51403', kind: 'fintech' },
  { name: 'Think Finance MFB', code: '677', kind: 'mfb' },
  { name: 'Titan Trust Bank', code: '102', kind: 'bank' },
  { name: 'Toprate MFB', code: '90801', kind: 'mfb' },
  { name: 'TransPay MFB', code: '090708', kind: 'mfb' },
  { name: 'Trustbanc J6 MFB', code: '51118', kind: 'mfb' },
  { name: 'U and C MFB', code: '50840', kind: 'mfb' },
  { name: 'UBA', code: '033', kind: 'bank' },
  { name: 'UBJ MFB', code: '51396', kind: 'mfb' },
  { name: 'UCEE MFB', code: '090706', kind: 'mfb' },
  { name: 'Uhuru MFB', code: '51322', kind: 'mfb' },
  { name: 'Ultraviolet MFB', code: '51080', kind: 'mfb' },
  { name: 'Umunnachi MFB', code: '51097', kind: 'mfb' },
  { name: 'Unaab MFB', code: '50870', kind: 'mfb' },
  { name: 'Uniabuja MFB', code: '51447', kind: 'mfb' },
  { name: 'Unical MFB', code: '50871', kind: 'mfb' },
  { name: 'Unilag MFB', code: '51316', kind: 'mfb' },
  { name: 'Unimaid MFB', code: '50875', kind: 'mfb' },
  { name: 'Union Bank', code: '032', kind: 'bank' },
  { name: 'Unity Bank', code: '215', kind: 'bank' },
  { name: 'UNIUYO MFB', code: '50880', kind: 'mfb' },
  { name: 'Uzondu MFB', code: '50894', kind: 'mfb' },
  { name: 'Vale Finance', code: '050020', kind: 'finance' },
  { name: 'VFD MFB', code: '566', kind: 'mfb' },
  { name: 'Victory MFB', code: '51085', kind: 'mfb' },
  { name: 'Vista MFB', code: '90787', kind: 'mfb' },
  { name: 'VTNetworks', code: 'C08', kind: 'fintech' },
  { name: 'Waya MFB', code: '51355', kind: 'mfb' },
  { name: 'Wema Bank', code: '035', kind: 'bank' },
  { name: 'Weston Charis MFB', code: '51386', kind: 'mfb' },
  { name: 'Whitecrust Finance Company', code: '402001', kind: 'finance' },
  { name: 'Xpress Wallet', code: '100040', kind: 'fintech' },
  { name: 'YCT MFB', code: '51253', kind: 'mfb' },
  { name: 'Yes MFB', code: '594', kind: 'mfb' },
  { name: 'Zap by Bitnob', code: '00zap', kind: 'fintech' },
  { name: 'Zenith Bank', code: '057', kind: 'bank' },
  { name: 'Zitra MFB', code: '51373', kind: 'mfb' },
];
